name: built-and-lint


# Trigger workflow on pull request or push to specific branches
on:
  pull_request:
    branches: [main, dev]
      # - main
  push:
    branches: [main, dev]
      # - main

    #   Define single or multiple jobs
jobs:
  built-and-lint:

    runs-on: ubuntu-latest
    #   Define the steps to be executed
    steps:
      # This basically checkout to your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # This basically setup the node.js environment
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # This basically print the node version
      - name: Print NODE Version
        run: node -v

      - name: Install Backend Dependencies
        working-directory: server
        run: npm ci

      - name: Fix Backend Linting
        working-directory: server
        run: npm run lint:fix

      - name: Lint Backend
        working-directory: server
        run: npm run lint -- --max-warnings 0

      - name: Install Frontend Dependencies
        working-directory: client
        run: npm ci

      - name: Fix Frontend Linting
        working-directory: client
        run: npm run lint:fix


      - name: Lint Frontend
        working-directory: client
        run: npm run lint -- --max-warnings 0

      - name: Build Backend Image
        run: docker build -t mern-backend ./server

      - name: Build Frontend Image
        run: docker build -t mern-frontend ./client


  deploy:
    # Dependency on Previous Job
    # Use needs to identify any jobs that must complete successfully before this job will run
    # If built-and-lint fails → deploy will not run.
    needs: built-and-lint
    if: github.event_name == 'push'
    # GitHub creates a temporary Ubuntu VM to run this job
    runs-on: ubuntu-latest
    steps:
      # This downloads your GitHub repository code into the runner.
      - name: Checkout (optional)
        uses: actions/checkout@v4

        # Add EC2 to known_hosts
        # Are you sure you want to continue connecting (yes/no)?
        # This would break CI pipelines.
        # So this step pre-approves the EC2 host.
      - name: Add EC2 host to known_host
      # Gets the public SSH key of the EC2 server
      # Adds it to known_hosts
        run: | 
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{secrets.EC2_HOST}}

      - name: Write SSH Key
      # Writes the secret SSH key into a file.
      # 600 = read + write for owner only
        run: | 
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
        env:
          EC2_KEY: ${{secrets.EC2_KEY}}

      - name: Deploy on EC2 (Here doing git pull + docker compose up -d --build)
        env: 
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_USER: ${{secrets.EC2_USER}}
          EC2_APP_DIR: ${{secrets.EC2_APP_DIR}}
        run: |
          ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << EOF
            set -e
            cd "${EC2_APP_DIR}"

            git fetch --all
            git reset --hard origin/main
            docker compose up -d --build
            docker image prune -f

            docker compose ps 
          EOF


